# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HCAudioUnitTest’ do
	pod 'HCMinizip'
	pod 'hccoren','~>0.3.3'
end
